# Rename this file name to "params.yaml" to use these example parameters.
# Fell free to modify :)

Run:
  name: Example.
  description: Example run.

Dataset:
  train_test_split: 0.7
  augmentation: False

CNN:
  convolutional_layers: 3
  filters_number: [16, 32, 64]
  kernel_size: 5
  polling_size: [5, 5]
  dense_layers_neurons_num: [64, 32, 16]
  batch_normalization: False
  batch_size: 45
  epochs: 15

ResNet:
  initial_filters: 16
  kernel_size: 5
  polling_size: [2, 2]
  residual_blocks: 2
  residual_filters_number: [32, 64]
  convolution_layers_inside_res_block: 3
  dense_layers_neurons_num: [128, 64, 32]
  batch_size: 45
  epochs: 15
